version: '3.8'

services:
  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - "6379:6379"

  web: &web
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 80:8000
    env_file: .env
    container_name: web

  celery_worker:
    <<: *web
    ports: [ ]
    command: celery -A config.celery worker -l INFO
    restart: always
    container_name: celery_worker
