version: '3.8'

services:
  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - "6379:6379"

  web: &web
    build:
      context: .
      dockerfile: Dockerfile.prod
    #command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file: .env
    container_name: web
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
      interval: 30s
      timeout: 10s
      retries: 5


  celery_worker:
    <<: *web
    ports: [ ]
    command: celery -A config.celery worker -l INFO
    restart: always
    container_name: celery_worker
    depends_on:
      web:
        condition: service_healthy

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env.prod.db
    container_name: db

volumes:
  postgres_data:
