version: '3.8'

services:
  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - "6379:6379"

  web: &web
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 80:8000
    env_file: .env
    depends_on:
      - db
    container_name: web

  celery_worker:
    <<: *web
    ports: [ ]
    command: celery -A config.celery worker -l INFO
    restart: always
    container_name: celery_worker

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env.dev.db
    container_name: db

volumes:
  postgres_data:
