# Generated by Django 4.2 on 2023-06-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="four_repr_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="content",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
