# Generated by Django 4.2 on 2023-07-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_content_four_repr_price_content_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="content",
            old_name="price",
            new_name="one_month_price",
        ),
    ]
