# Generated by Django 4.2 on 2023-06-22 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "content_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.content",
                    ),
                ),
                (
                    "cover",
                    models.FileField(blank=True, null=True, upload_to="preventa/audio/cover/%Y/%m"),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="preventa/audio/file/%Y/%m"),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(default=0, verbose_name="Duration in seconds"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("common.content",),
        ),
        migrations.CreateModel(
            name="UserContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserContentPaymentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "payment_plan",
                    models.CharField(
                        choices=[
                            ("one_time", "ONE TIME"),
                            ("four_time_reproduction", "Four Time Reproduction"),
                            ("one_month", "ONE MONTH"),
                            ("one_day", "ONE DAY"),
                        ],
                        default="one_time",
                        max_length=255,
                        verbose_name="Type",
                    ),
                ),
                (
                    "available_reproductions",
                    models.IntegerField(
                        default=4,
                        help_text="Used when content is bought for 4 repro...",
                    ),
                ),
                (
                    "limited_reproduction",
                    models.BooleanField(default=False, verbose_name="Limited Reproduction"),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.content",
                        verbose_name="Content",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
