# Generated by Django 4.2 on 2023-06-18 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payment", "0001_initial"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "content_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.content",
                    ),
                ),
                (
                    "cover",
                    models.FileField(blank=True, null=True, upload_to="preventa/audio/cover/%Y/%m"),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="preventa/audio/file/%Y/%m"),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(default=0, verbose_name="Duration in seconds"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("common.content",),
        ),
        migrations.CreateModel(
            name="UserContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "watched_time",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Used when content is bought for 4 repro...",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payment.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "preventa_audio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="preventa.audio",
                        verbose_name="Bought Audio",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
