# Generated by Django 4.2 on 2023-06-19 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_initial"),
        ("preventa", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercontentpaymentplan",
            name="available_reproductions",
            field=models.IntegerField(default=4, help_text="Used when content is bought for 4 repro..."),
        ),
        migrations.AlterField(
            model_name="usercontentpaymentplan",
            name="content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_payment_plans",
                to="common.content",
                verbose_name="Content",
            ),
        ),
    ]
