# Generated by Django 4.2 on 2023-06-23 14:40

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preventa", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=config.storage_backends.PrivateMediaStorage(),
                upload_to="preventa/audio/file/%Y/%m",
            ),
        ),
    ]
