# Generated by Django 4.2 on 2023-06-26 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_transaction"),
        ("preventa", "0003_alter_audio_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercontentpaymentplan",
            name="order",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="payment.order",
                verbose_name="Order",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="usercontentpaymentplan",
            name="payment_plan",
            field=models.CharField(
                choices=[
                    ("one_time", "One Time"),
                    ("four_time", "Four Time"),
                    ("one_month", "One Month"),
                    ("one_day", "One Day"),
                ],
                default="one_time",
                max_length=255,
                verbose_name="Type",
            ),
        ),
    ]
