# Generated by Django 4.2 on 2023-07-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preventa", "0005_alter_usercontentpaymentplan_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercontentpaymentplan",
            name="limited_reproduction",
            field=models.BooleanField(default=True, verbose_name="Limited Reproduction"),
        ),
    ]
