# Generated by Django 4.2 on 2023-07-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("preventa", "0006_alter_usercontentpaymentplan_limited_reproduction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercontentpaymentplan",
            name="limited_reproduction",
        ),
        migrations.AddField(
            model_name="usercontentpaymentplan",
            name="expiration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
