# Generated by Django 4.2 on 2023-06-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="middle_name",
        ),
        migrations.AddField(
            model_name="user",
            name="is_creator",
            field=models.BooleanField(default=False, verbose_name="Is Creator"),
        ),
    ]
