# Generated by Django 4.2 on 2023-06-22 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_initial"),
        ("payment", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="audio",
        ),
        migrations.AddField(
            model_name="order",
            name="content",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="common.content",
                verbose_name="Content",
            ),
        ),
    ]
