# Generated by Django 4.2 on 2023-06-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_remove_order_audio_order_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="type",
        ),
    ]
