# Generated by Django 4.2 on 2023-06-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0006_flowcustomer"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="flowcustomer",
            unique_together=set(),
        ),
    ]
