# Generated by Django 4.2 on 2023-06-30 11:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payment", "0007_alter_flowcustomer_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="flowcustomer",
            unique_together={("cliente", "flow_customer_id")},
        ),
    ]
