# Generated by Django 4.2 on 2023-07-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0008_alter_flowcustomer_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usercard",
            old_name="card_id",
            new_name="last_four_digits",
        ),
        migrations.RenameField(
            model_name="usercard",
            old_name="token",
            new_name="registration_token",
        ),
        migrations.RenameField(
            model_name="usercard",
            old_name="card_number",
            new_name="type",
        ),
        migrations.AlterUniqueTogether(
            name="usercard",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="usercard",
            name="expire_date",
        ),
    ]
