# Generated by Django 4.2 on 2023-07-01 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payment", "0009_rename_card_id_usercard_last_four_digits_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowcustomer",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="flow_customer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="provider",
            field=models.CharField(
                choices=[("flow", "FLOW"), ("card", "CARD")],
                max_length=63,
                verbose_name="Provider",
            ),
        ),
    ]
