# Generated by Django 4.2 on 2023-07-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0010_alter_flowcustomer_cliente_alter_order_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("canceled", "Canceled"),
                ],
                default="waiting",
                max_length=63,
                verbose_name="Status",
            ),
        ),
    ]
