# Generated by Django 4.2 on 2023-07-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0011_alter_transaction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercard",
            name="last_four_digits",
            field=models.CharField(max_length=255, verbose_name="Last Four Digits"),
        ),
        migrations.AlterField(
            model_name="usercard",
            name="registration_token",
            field=models.CharField(max_length=255, null=True, verbose_name="Registration Token"),
        ),
        migrations.AlterField(
            model_name="usercard",
            name="type",
            field=models.CharField(max_length=255, verbose_name="Type"),
        ),
    ]
